# Generated by Django 3.0.8 on 2020-07-04 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 13, 2, 52, 684428, tzinfo=utc)),
        ),
    ]
