# Generated by Django 3.0.8 on 2020-07-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost2',
            name='likes',
        ),
    ]
