# Generated by Django 3.0.8 on 2020-07-04 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='BlogPost',
            new_name='blogpost',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 13, 27, 10, 788442, tzinfo=utc)),
        ),
    ]
