# Generated by Django 3.0.8 on 2020-07-04 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200704_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
